/*
 * XYZWriter.cpp
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#include "io/XYZWriter.h"

#include <filesystem>
#include <iomanip>
#include <iostream>
#include <sstream>

namespace outputWriter {

XYZWriter::XYZWriter() = default;

XYZWriter::~XYZWriter() = default;

void XYZWriter::plotParticles(const std::vector<Particle>& particles, const std::string& filename, int iteration) {
  // create separate output directory
  const std::string output_directory = "output";
  try {
    std::filesystem::create_directories(output_directory);
  } catch (const std::filesystem::filesystem_error& err) {
    std::cerr << "Error wile creating directory " << output_directory << ": " << err.what() << std::endl;
    return;
  }

  std::ofstream file;
  std::stringstream strstr;
  strstr << output_directory << "/" << filename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

  file.open(strstr.str().c_str());
  file << particles.size() << std::endl;
  file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
          "file format doku."
       << std::endl;

  for (auto& p : particles) {
    std::array<double, 3> x = p.getX();
    file << "Ar ";
    file.setf(std::ios_base::showpoint);

    for (auto& xi : x) {
      file << xi << " ";
    }

    file << std::endl;
  }

  file.close();
}

}  // namespace outputWriter
