/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include <iostream>

#include "Particle.h"

#include "utils/ArrayUtils.h"

Particle::Particle(int type_arg)
    : x{0.0, 0.0, 0.0},
      v{0.0, 0.0, 0.0},
      f{0.0, 0.0, 0.0},
      old_f{0.0, 0.0, 0.0},
      m(0.0),
      type(type_arg) {
  // Debug:
  // std::cout << "Particle generated!" << std::endl;
}

/*
 * The Copy constructor is defaulted in Particle.h
 * Replace it with the commented implementation for debugging purposes.
 */

/*Particle::Particle(const Particle &other) {
  x = other.x;
  v = other.v;
  f = other.f;
  old_f = other.old_f;
  m = other.m;
  type = other.type;
  std::cerr << "Particle generated by copy!" << std::endl;
}*/

Particle::Particle(const std::array<double, 3>& x_arg,
                   const std::array<double, 3>& v_arg, const double m_arg,
                   const int type_arg)
    : x(x_arg),
      v(v_arg),
      f{0., 0., 0.},
      old_f{0., 0., 0.},
      m(m_arg),
      type(type_arg) {
  // Debug:
  // std::cout << "Particle generated!" << std::endl;
}

// Getters
const std::array<double, 3>& Particle::getX() const {
  return x;
}

const std::array<double, 3>& Particle::getV() const {
  return v;
}

const std::array<double, 3>& Particle::getF() const {
  return f;
}

const std::array<double, 3>& Particle::getOldF() const {
  return old_f;
}

double Particle::getM() const {
  return m;
}

int Particle::getType() const {
  return type;
}

std::string Particle::toString() const {
  std::stringstream stream;
  stream << "Particle: X:" << x << " v: " << v << " f: " << f
         << " old_f: " << old_f << " type: " << type;
  return stream.str();
}

bool Particle::operator==(const Particle& other) const {
  return (x == other.x) and (v == other.v) and (f == other.f) and
         (type == other.type) and (m == other.m) and (old_f == other.old_f);
}

std::ostream& operator<<(std::ostream& stream, const Particle& p) {
  stream << p.toString();
  return stream;
}
